// Channels
export const SET_CURRENT_CHANNEL = 'SET_CURRENT_CHANNEL';
export const SET_PRIVATE_CHANNEL = 'SET_PRIVATE_CHANNEL';
export const SET_CHANNEL_USERS_POST_COUNTS = 'SET_CHANNEL_USERS_POST_COUNTS';

// User
export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';